src/IceRpc.Templates/Directory.Build.props

Fix #3645 
The icon and other NuGet settings are defined in `build/Common.props`, but the file was not included in this project.

Include Common.props in IceRpc.Templates project

---

build/IceRpc.Src.props

See https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#continuousintegrationbuild
Fix #3644

Enable CI build for GitHub builds

---

src/IceRpc/Internal/IceDuplexConnectionDecorator.cs
src/IceRpc/Internal/IceProtocolConnection.cs
src/IceRpc/Transports/Slic/Internal/SlicConnection.cs
src/IceRpc/Transports/Slic/Internal/SlicDuplexConnectionDecorator.cs
tests/IceRpc.Tests/IceIdleTimeoutTests.cs
tests/IceRpc.Tests/Transports/Slic/SlicIdleTimeoutTests.cs
tests/IceRpc.Tests/Transports/Slic/SlicTransportTests.cs

This PR refactors how Slic keeps connections alive.
Fixes #3665.
With this new implementation, Slic keeps connection alive by sending Ping frames from client connections (like before).
The algorithm is now:
- send a Ping frame idle timeout * 0.6 after the last write even if there is an outstanding pong (= like before, except it's now 0.6 instead of 0.5)
-  send a Ping frame idle timeout * 0.5 after the last read unless there is already an outstanding pong (new)
This PR also refactors the idle timeout decorator and associated tests. They are now 2 separate decorators, one for Ice and one for Slic. This PR didn't change the Ice logic.

Refactors how Slic keeps connections alive

---

tools/slicec-cs/Cargo.toml

We now specify the **m**inimum **s**upported **r**ust **v**ersion (MSRV) in our Cargo file.
Note that the MSRV didn't change, it has been `1.70` since before we released.
But now, if someone has an old compiler, instead of failing part-way through compilation,
Cargo will immediately fail, and emit a much more helpful error message.

Document the MSRV in our Cargo file.

---

.github/workflows/ci.yml
build/Tests.runsettings
tests/IceRpc.Conformance.Tests/Transports/MultiplexedListenerConformanceTests.cs
tests/IceRpc.Tests/AssemblyInfo.cs

- For the QUIC Connect_fails_if_listener_is_disposed conformance test, successful connections must be disposed to ensure timely failures for new connections.
- Updated the CI job to use a larger 8-core runner.
- Limit test runners to 8 globally: some SSL tests were running slow with higher concurrency.

Connect_fails_if_listener_is_disposed test simplifications

---

src/IceRpc/Router.cs

According to https://devblogs.microsoft.com/dotnet/performance-improvements-in-aspnet-core-8/, Frozen dictionary is significantly faster for the "router" use-case.

Use FrozenDictionary in Router

---

tools/IceRpc.Slice.Tools/src/IceRpc.Slice.Tools/IceRpc.Slice.Tools.props

Minor cleanup to IceRpc.Slice.Tools:
- Removed Omnisharp workaround
- Rename some internal properties for consistency with IceRpc.Protobuf.Tools

Slice tools cleanup

---

build/Tests.runsettings
tests/IceRpc.Quic.Tests/Transports/QuicTransportConformanceTests.cs
tests/IceRpc.Quic.Tests/Transports/QuicTransportSslAuthenticationTests.cs
tests/IceRpc.Quic.Tests/Transports/QuicTransportTests.cs

There are a number of QUIC tests that are frequently failing, which seems can be related to https://github.com/dotnet/runtime/issues/55979
This PR adds NonParallelizable attribute to all QUIC test fixtures and also reduces the number of test workers to 4, with these changes I have been running the test suite in a loop for several hours without failures, let's see if it results in more stable CI builds too.
Fixes #3696
Fixes #3701

Run QUIC tests serially

---

src/IceRpc.Protobuf.Generators/Internal/DiagnosticDescriptors.cs
src/IceRpc.Protobuf.Generators/Internal/Emitter.cs
src/IceRpc.Protobuf.Generators/Internal/Parser.cs
src/IceRpc.Protobuf.Generators/Internal/ServiceMethod.cs
src/IceRpc.Protobuf/ProtobufOperationAttribute.cs
src/IceRpc.Protobuf/ProtobufServiceAttribute.cs
tools/IceRpc.ProtocGen/ServiceGenerator.cs

This PR removes the ProtobufD methods generated by IceRpc.ProtocGen.
They are replaced by better code generated by the Protobuf Service source generator.

Remove ProtobufD methods

---

tests/IceRpc.Protobuf.Tests/OperationTests.cs
tests/IceRpc.Protobuf.Tests/OperationTests.proto

This PR adds a test for Protobuf idempotency_level usage with IceRPC

Protobuf idempotent test

---

tests/IceRpc.Protobuf.Tests/PipeReaderExtensionsTests.cs

This PR adds a test to ensure that `DecodeProtobufMessageAsync` throws `InvalidDataException` when the max message length is exceeded.

Add test for Protobuf max message length

---

examples/StreamProtobuf/proto/generator.proto
tests/IceRpc.Protobuf.Tests/OperationTests.proto

Use the standard Protobuf naming conventions

---

.devcontainer/Dockerfile

Update devcontainer configuration to uset .NET 8 images. Released yesterday as part of https://github.com/devcontainers/images/pull/852

Use .NET 8 docker images for devcontainer

---

tools/IceRpc.ProtocGen/Program.cs
tools/IceRpc.ProtocGen/StringExtensions.cs

Fix #3759
I added a helper method to remove that allows removing extra empty lines, because I think is nice to be able to use the string templates in the generators. I think the string templates make it easy to see what the generator produces.

Remove extra blank lines in Protobuf generated code

---

src/Directory.Build.props
src/IceRpc.Slice/IceRpc.Slice.csproj
src/IceRpc/IceRpc.csproj
src/ZeroC.Slice/ZeroC.Slice.csproj

This PR fixes the build to include the source link package with all src projects. It also upgraded the version to 8.0.x (latest stable).

Upgrade source link package

---

tools/IceRpc.Protobuf.Tools/ProtocTask.cs

Parse protoc errors to log with MSBuild logger

---

tests/IceRpc.Protobuf.Tests/OperationTests.cs
tests/IceRpc.Tests.Common/ColocInvoker.cs

This PR adds tests to ensure that IceRpc+Protobuf integration completes the request and response payloads, there is also a minor fix for the ColocInvoker used by some tests, which didn't complete the outgoing frame payloads.

Add tests to ensure that IceRpc+Protobuf completes the payloads

---

src/IceRpc.Slice/ProxySliceDecoderExtensions.cs
src/ZeroC.Slice/SliceDecoder.cs
src/ZeroC.Slice/SliceEncoderExtensions.cs

The goal is to make ZeroC.Slice even more proxy-independent. See also https://github.com/icerpc/slicec/issues/673.

Remove references to Proxy from ZeroC.Slice

---

docfx/docfx.json
docfx/index.md
docfx/namespaces/IceRpc.Protobuf.md

This PR updates the doc index page to include links for protobuf.

Add Protobuf to the doc index page

---

.vscode/settings.json

This PR adds slice extension configuration settings to only look at the `slice` folder. Without this setting, the extension tries to compile all slice in the workspace, resulting in lots of redefinition errors.
**Edit**: Also the `"cSpell.showStatus": true`, was not doing anything so I removed it.

Configure slice extension

---

BUILDING.md

I just updated the required SDK, with the main branch we need the .NET 8 SDK. There are also a few fixes for the Markdown linter warnings.

Update build instructions to use .NET 8 SDK

---

tools/slicec-cs/src/cs_attributes/cs_identifier.rs

This small PR implements #3805.

Support 'cs::identifier' on custom types.

---

slice/Ice/Locator.slice
slice/Ice/LocatorRegistry.slice
slice/Ice/Object.slice
slice/Ice/Process.slice
tests/IceRpc.Slice.Tests/ProxyTests.cs
tests/IceRpc.Slice.Tests/ProxyTests.slice
tests/IntegrationTests/ProtocolBridgingTests.slice
tools/slicec-cs/src/generators/proxy_generator.rs

This PR generates encode/decode methods for proxies, and adds a number of custom *Name*Proxy types.
Fixes #3803.

Generate encode/decode extension methods for proxies

---

slice/Ice/Object.slice
tests/IceRpc.Slice.Tests/ProxyTests.cs
tests/IceRpc.Slice.Tests/ProxyTests.slice

This PR adds `cs::identifier` to ObjectProxy and adds a test to make sure it works.

Use cs::identifier for ObjectProxy, add test

---

tests/IceRpc.Slice.Tests/OperationTests.slice
tests/IceRpc.Slice.Tests/Pingable.slice
tests/IceRpc.Slice.Tests/StructTests.Slice1.slice
tests/IceRpc.Slice.Tests/StructTests.cs
tools/slicec-cs/Cargo.lock
tools/slicec-cs/Cargo.toml
tools/slicec-cs/src/builders.rs
tools/slicec-cs/src/cs_attributes/cs_identifier.rs
tools/slicec-cs/src/cs_compile.rs
tools/slicec-cs/src/cs_util.rs
tools/slicec-cs/src/decoding.rs
tools/slicec-cs/src/encoding.rs
tools/slicec-cs/src/generators/mod.rs
tools/slicec-cs/src/slicec_ext/comment_ext.rs
tools/slicec-cs/src/slicec_ext/type_ref_ext.rs

This PR updates the dependencies of `slicec-cs` including bringing in the latest `slicec`.
- Interfaces can no longer be used as types. To use them, you must create a custom type instead.
- While implementing this I came across a bug and had to comment out a test for now. See #3812,
- `slicec` added better location tracking for doc comment components and `slicec-cs` now uses these.
- Visitor function provide a default no-op implementation, so we don't need to have them anymore.
- Added a check that rejects enums without underlying types in `Slice2` files (now that the parser supports them). See #3809.

Updated slicec-cs to use the latest version of slicec

---

tools/slicec-cs/src/decoding.rs

When we decode a type, it's obviously non-null (we just decoded it).
If the type it's being assigned to _is_ null though, we need to cast it. Currently, the decoding code-gen does this in 2 separate ways.
- For optional _value_ types, we do `... as type?`
- For optional _reference_ types, we do `(type?)`
It's simpler and easier to only use one of these, instead of using a different cast for each.
Both would work, I ultimately chose the `(type?)` cast as it seems slightly safer (it throws an exception for bad casts).
I tried both. Neither allowed for any more simplification than the other.
It would take a matter of seconds to switch to using the `as` syntax though. Just let me know what everyone's preferences are.

Simplified how we cast optional types in decoding functions.

---

tests/IceRpc.Slice.Tests/StructTests.Slice1.slice
tests/IceRpc.Slice.Tests/StructTests.cs
tools/slicec-cs/src/encoding.rs
tools/slicec-cs/src/member_util.rs
tools/slicec-cs/src/slicec_ext/type_ref_ext.rs

Fix encoding of optional custom types

---

tools/IceRpc.Slice.Tools/IceRpc.Slice.Tools.csproj

Fix #3817 
After asking for directions in MSBuild discord channel, bundling the task dependencies seems to be the safer approach.

Bundle IceRpc.Slice.Tools dependencies with the task

---

tests/IceRpc.Slice.Tests/DictionaryMappingTests.cs
tests/IceRpc.Slice.Tests/DictionaryMappingTests.slice
tests/IceRpc.Slice.Tests/SequenceMappingTests.cs
tests/IceRpc.Slice.Tests/SequenceMappingTests.slice
tests/ZeroC.Slice.Tests/WellKnownTypes.slice
tests/ZeroC.Slice.Tests/WellKnownTypesTests.cs

Add more tests for custom types

---

src/IceRpc.Slice/IProxy.cs
src/IceRpc.Slice/ProxySliceDecoderExtensions.cs
src/IceRpc.Slice/SliceServiceProviderExtensions.cs
src/IceRpc/InvalidInvoker.cs
tests/IceRpc.Slice.Tests/InvalidProxy.cs
tests/IceRpc.Slice.Tests/OperationTests.cs
tests/IceRpc.Slice.Tests/ProxyTests.cs
tests/IceRpc.Slice.Tests/StructTests.cs
tests/IntegrationTests/ProtocolBridgingTests.cs
tools/slicec-cs/src/generators/proxy_generator.rs

This PR makes IProxy.Invoker not nullable, just like IProtobufClient.Incoker.
Rather than null, the code now uses  InvalidInvoker.Instance when it needs an invalid invoker - typically when the proxy is used for encoding and not for invoking.

Make IProxy.Invoker not nullable

---

tests/ZeroC.Slice.Tests/StructTests.cs
tools/slicec-cs/src/member_util.rs
tools/slicec-cs/src/slicec_ext/member_ext.rs
tools/slicec-cs/src/slicec_ext/mod.rs

This PR changes the mapping for Slice fields. Prior to this PR, they were mapped to C# fields. This PR maps them to C# properties.
Rationale:
- C# prefers auto-implemented public properties over public fields
- for `cs::readonly` struct, you can now clone a readonly struct with `with` - this didn't work with readonly fields
- it's consistent with the mapping for enum fields
Fixes #3858 
Note: this PR changes the mapping for all fields (struct, class, exception), not just struct fields.

Map Slice fields to C# properties

---

tests/ZeroC.Slice.Tests/EnumWithFieldsTests.cs
tests/ZeroC.Slice.Tests/EnumWithFieldsTests.slice

This new test verifies that `[cs::attribute]` works for enumerators in enum with fields.

Add test for enumerator attribute

---

tools/slicec-cs/src/builders.rs
tools/slicec-cs/src/cs_util.rs
tools/slicec-cs/src/decoding.rs
tools/slicec-cs/src/encoding.rs
tools/slicec-cs/src/generators/class_generator.rs
tools/slicec-cs/src/generators/dispatch_generator.rs
tools/slicec-cs/src/generators/enum_generator.rs
tools/slicec-cs/src/generators/exception_generator.rs
tools/slicec-cs/src/generators/struct_generator.rs
tools/slicec-cs/src/member_util.rs
tools/slicec-cs/src/slicec_ext/member_ext.rs
tools/slicec-cs/src/slicec_ext/operation_ext.rs

This PR removes the field name escaping (or mangling), where we would add a Slice prefix to a mapped field name if it matched `Equals` or other various common methods. 
It was not really correct since we didn't apply this logic to struct fields.
After this PR, a user with a field named `Equals` needs to remap it with `cs::identifier`. Otherwise, he'll get a C# compilation error.
Fixes #3859

Remove field name escaping

---

build/CodeAnalysis.Base.globalconfig
src/ZeroC.Slice/IActivator.cs
src/ZeroC.Slice/Internal/Activator.cs
src/ZeroC.Slice/SliceDecoder.Class.cs
tests/ZeroC.Slice.Tests/ActivatorTests.cs
tests/ZeroC.Slice.Tests/SlicingTests.cs
tests/ZeroC.Slice.Tests/TaggedTests.cs
tools/slicec-cs/src/generators/class_generator.rs
tools/slicec-cs/src/generators/exception_generator.rs

This PR simplifies the Activator API by removing the unused `ref SliceDecoder` parameter.
Fixes #3876.

Simplify Activator API

---

src/ZeroC.Slice/Result.cs
src/ZeroC.Slice/SliceDecoderExtensions.cs
src/ZeroC.Slice/SliceEncoderExtensions.cs
src/ZeroC.Slice/ZeroC.Slice.csproj
tests/IceRpc.Slice.Tests/OperationTests.cs
tests/IceRpc.Slice.Tests/OperationTests.slice
tests/ZeroC.Slice.Tests/ResultTests.cs
tests/ZeroC.Slice.Tests/ResultTests.slice
tests/ZeroC.Slice.Tests/ZeroC.Slice.Tests.csproj
tools/slicec-cs/Cargo.lock
tools/slicec-cs/Cargo.toml
tools/slicec-cs/src/decoding.rs
tools/slicec-cs/src/encoding.rs
tools/slicec-cs/src/slicec_ext/type_ref_ext.rs

This PR maps the new Slice built-in generic type Result<Success, Failure> to C#.
It also updates Dunet from version 1.10 to 1.11. Note that Dunet is now a runtime dependency (for the Dunet.Union attribute).
Fixes #3875.

Update slicec-cs to generate code for Result<Success, Failure>

---

tests/IceRpc.Slice.Tests/DictionaryMappingTests.slice
tests/IceRpc.Slice.Tests/SequenceMappingTests.slice
tools/slicec-cs/src/cs_attributes/cs_identifier.rs
tools/slicec-cs/src/decoding.rs
tools/slicec-cs/src/encoding.rs

This small PR fixes the bug found in #3881, and fixes an identical bug that was causing dictionaries to break too.
In both cases we weren't correctly handled collections of optional collections. We perform a cast on the inner collection, and these casts weren't taking nullability into account when they needed to.
It also adds some 'tests', which just ensures that the generated code compiles.
Apart from the small test added in this PR, we have no tests for nested dictionaries in Slice.
We should probably add some.
@bernardnormier believes we can avoid these casts altogether by moving them into the factory.
But for now I'd like to get the bug fixed and some basic tests in place before we worry about cleaning things up.

Fix Broken Code Generation for Nested Optional Collections (Fixes #3881)

---

tools/slicec-cs/src/builders.rs
tools/slicec-cs/src/decoding.rs
tools/slicec-cs/src/encoding.rs
tools/slicec-cs/src/generators/class_generator.rs
tools/slicec-cs/src/generators/dispatch_generator.rs
tools/slicec-cs/src/generators/enum_generator.rs
tools/slicec-cs/src/generators/exception_generator.rs
tools/slicec-cs/src/generators/proxy_generator.rs
tools/slicec-cs/src/generators/struct_generator.rs
tools/slicec-cs/src/member_util.rs

This PR performs some cleanup in `slicec-cs`. No logic or function is altered by this PR, it just cleans and refactors.
It removes 86 lines of code.
I'm only opening a PR to make sure CI passes. But if you want to review it, go for it!

`slicec-cs` Cleanup Pass 1

---

tests/ZeroC.Slice.Tests/EnumWithFieldsTests.slice
tools/slicec-cs/src/builders.rs
tools/slicec-cs/src/generators/dispatch_generator.rs
tools/slicec-cs/src/generators/enum_generator.rs
tools/slicec-cs/src/generators/proxy_generator.rs
tools/slicec-cs/src/slicec_ext/member_ext.rs

This PR updates slicec-cs to generate doc-comments (`<param name="..." ... />`) from @param doc comments on Slice enumerators.

Generate doc comment for @param on enumerator fields

---

tools/slicec-cs/src/decoding.rs
tools/slicec-cs/src/encoding.rs
tools/slicec-cs/src/generators/class_generator.rs
tools/slicec-cs/src/generators/enum_generator.rs
tools/slicec-cs/src/generators/exception_generator.rs
tools/slicec-cs/src/generators/struct_generator.rs

This PR performs some more cleanup in slicec-cs. No logic or function is altered by this PR, it just cleans and refactors.
It removes 54 lines of code (for a running total of 140 lines).
I'm only opening a PR to make sure CI passes. But if you want to review it, go for it!

slicec-cs Cleanup Pass 2

---

tools/slicec-cs/src/builders.rs
tools/slicec-cs/src/decoding.rs
tools/slicec-cs/src/encoding.rs
tools/slicec-cs/src/generators/class_generator.rs
tools/slicec-cs/src/generators/dispatch_generator.rs
tools/slicec-cs/src/generators/exception_generator.rs
tools/slicec-cs/src/generators/proxy_generator.rs
tools/slicec-cs/src/generators/struct_generator.rs
tools/slicec-cs/src/member_util.rs
tools/slicec-cs/src/slicec_ext/member_ext.rs
tools/slicec-cs/src/slicec_ext/operation_ext.rs
tools/slicec-cs/src/slicec_ext/type_ref_ext.rs

This PR is a first step towards refactoring our `cs_type_string` functions:
Currently, `TypeRefExt::cs_type_string` takes a `TypeContext`, and has 3 different behaviors depending the type-context.
This PR splits this function into 3: `field_type_string`, `incoming_parameter_type_string`, and `outgoing_parameter_type_string`.
The behavior is identical to before, I've just split each context's match case into a standalone function.
Note that `ParameterExt` has it's own function also named `cs_type_string`.
I will deal with this in my next PR, but wanted to split it up to keep these easy to review.
`ParameterExt::cs_type_string` took a `bool: ignore_optional`, but this was _always_ false, so I removed the parameter and hard-coded false. Otherwise this function was left alone.

Split up `TypeRefExt::cs_type_string`

---

docfx/docfx.json
docfx/filterConfig.yml
src/ZeroC.Slice/Result.cs

This PR fixes #3892  (second option).

Filter out Dunet-generated API from docfx since it has no doc-comments

---

tools/slicec-cs/src/decoding.rs
tools/slicec-cs/src/generators/dispatch_generator.rs
tools/slicec-cs/src/generators/proxy_generator.rs
tools/slicec-cs/src/slicec_ext/member_ext.rs

We have the function `parameter_name_with_prefix`, which accepts an arbitrary prefix and computes the
'parameter string representation' of a member, with that prefix.
This prefix is always `sliceP_` and this PR simplifies the logic by hard-coding this value.
It also adds doc comments to the 2 functions it touches.

Hardcode 'sliceP_' Prefix.

---

tools/slicec-cs/Cargo.lock
tools/slicec-cs/src/builders.rs
tools/slicec-cs/src/code_gen_util.rs
tools/slicec-cs/src/decoding.rs
tools/slicec-cs/src/encoding.rs
tools/slicec-cs/src/generators/class_generator.rs
tools/slicec-cs/src/generators/dispatch_generator.rs
tools/slicec-cs/src/generators/enum_generator.rs
tools/slicec-cs/src/generators/mod.rs
tools/slicec-cs/src/generators/proxy_generator.rs
tools/slicec-cs/src/generators/struct_generator.rs
tools/slicec-cs/src/main.rs
tools/slicec-cs/src/slicec_ext/member_ext.rs
tools/slicec-cs/src/slicec_ext/operation_ext.rs

This PR pulls in the latest changes from `slicec`.
These include a simplified CodeBlock API, that saves us a `mut` and `&` in places,
and it moves the `code_gen_util` types out of `slicec` and into `slicec-cs`.

Pull in latest 'slicec'.

---

tools/slicec-cs/src/decoding.rs
tools/slicec-cs/src/generators/dispatch_generator.rs
tools/slicec-cs/src/generators/proxy_generator.rs

This PR reworks and renames `decode_operation`, so it not longer takes a random bool parameter.
This parameter was only used to pick either the parameters, or return members from an operation. Now this is left up to caller to pass in.

Remove `is_dispatch` flag from `decode_operation`

---

tools/slicec-cs/src/decoding.rs
tools/slicec-cs/src/generators/dispatch_generator.rs
tools/slicec-cs/src/generators/proxy_generator.rs

This PR merges `request_decode_func` and `return_value_decode_func` into a single function, since they were actually identical functions. This new function is named: `decode_non_streamed_parameters_func`.
It was fairly small, and after this change, `decode_non_streamed_parameters` was only called in one spot, in this function, so I also went ahead and inlined the function there.

Merge `request_decode_func` and `return_value_decode_func`

---

tools/slicec-cs/src/decoding.rs

After investigating the way we cast sequences and dictionaries, I noticed we're accidentally generating a double cast for optional nested sequences and dictionaries. One that we always generate for lambdas, and another we always generate for sequences and dictionaries. This PR removes removes the double-cast:
```diff
size => new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.IDictionary<string, bool>?>(size),
(ref SliceDecoder decoder) => decoder.DecodeString(),
-                (ref SliceDecoder decoder) => (global::System.Collections.Generic.Dictionary<string, bool>?)decoder.DecodeDictionary(
+                (ref SliceDecoder decoder) => decoder.DecodeDictionary(
size => new global::System.Collections.Generic.Dictionary<string, bool>(size), …
```

Remove redundant cast in 'decode_func_body' for collections.

---

tools/slicec-cs/src/generators/dispatch_generator.rs
tools/slicec-cs/src/generators/proxy_generator.rs
tools/slicec-cs/src/slicec_ext/operation_ext.rs

We have a `return_task` function which takes an `is_dispatch` bool.
Almost everything in this function is just `if is_dispatch {} else {}`, so this PR just splits it into two separate functions:
`dispatch_return_task` and `invocation_return_task`.
We re-implemented this function in the body of `response_class`.
So, this PR also changes that logic to just call the new `invocation_return_task`.

Split return task func

---

tests/ZeroC.Slice.Tests/CustomTypeTests.cs
tests/ZeroC.Slice.Tests/CustomTypeTests.slice
tests/ZeroC.Slice.Tests/DictionaryDecodingTests.cs
tests/ZeroC.Slice.Tests/DictionaryEncodingTests.cs
tests/ZeroC.Slice.Tests/NumericTypesEncodingTests.cs
tests/ZeroC.Slice.Tests/SequenceDecodingTests.cs
tests/ZeroC.Slice.Tests/StructTests.cs
tools/slicec-cs/src/decoding.rs
tools/slicec-cs/src/encoding.rs

This PR adds more comprehensive testing for custom types in Slice1 contexts and fixes #3918,
which caused `slicec-cs` to treat tagged custom types as _optional_ (untagged) custom types.
The only way to test this was with classes (the only Slice1 type that can hold tags).
But, this means the class encoding bleeds into what should be a test purely for custom types.
Maybe this is just how it is, but if anyone has any ideas to avoid this, they'd be welcome!

Fix Tagged Custom Types with Slice1

---

tools/slicec-cs/Cargo.lock
tools/slicec-cs/Cargo.toml
tools/slicec-cs/src/encoding.rs

This PR simplifies the logic of `encode_action_body` and fixes a bug with
the encoding of tagged custom types (which map to C# value types) in Slice1 mode (quite niche).
----
For example, take this snippet:
```slice
class Hello {
tag(1) d1: CustomType?
}
```
We currently generate this:
```
encoder.StartSlice(SliceTypeId);
if (this.D1 is MyCustomType d1_)
{
encoder.EncodeTagged(1, TagFormat.FSize, d1_, (ref SliceEncoder encoder, MyCustomType value) => CustomTypeSliceEncoderExtensions.EncodeNullableCustomType(ref encoder, value));
}
encoder.EndSlice(true);
```
Notably, this calls `EncodeNullableCustomType` which is incorrect. We know here that `value` is non-null.
Even the type of the lambda is `MyCustomType`, with no `?` suffix.
This PR fixes this to call the non-nullable function:
``` …
```

Simplify 'encode_action_body'.

---

tools/slicec-cs/src/builders.rs
tools/slicec-cs/src/decoding.rs
tools/slicec-cs/src/slicec_ext/enum_ext.rs

This PR untangles and simplifies the `decode_sequence` function.
Before this PR, it was (probably) the longest function in `slicec-cs` at 153 lines long. Now it's only 63 (and easier to read too).
I don't expect the changes to this function to be reviewable, but I'm _pretty_ sure no logic has been altered. So it's fine! 😉
What is worth reviewing are the smaller changes it makes to `FunctionCallBuilder`:
- Now you can specify type parameters for calling generic functions
- We no longer print arguments on multiple lines if there are 0 arguments.

Simplify `decode_sequence` function.

---

build/IceRpc.Version.props
src/IceRpc.Templates/Templates/IceRpc-Protobuf-Client/IceRpc-Protobuf-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-DI-Client/IceRpc-Protobuf-DI-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-DI-Server/IceRpc-Protobuf-DI-Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-Server/IceRpc-Protobuf-Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-Client/IceRpc-Slice-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Client/IceRpc-Slice-DI-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Server/IceRpc-Slice-DI-Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-Server/IceRpc-Slice-Server.csproj
tools/slicec-cs/Cargo.lock
tools/slicec-cs/Cargo.toml

All the issues are closed, everything seems green, so this PR updates `icerpc-csharp` `0.3.0` to no longer be a preview.

Update version from '0.3.0-preview1' to '0.3.0'.

---

.vscode/cspell.json
src/ZeroC.Slice/SliceEncoder.cs
tests/ZeroC.Slice.Tests/CustomTypeTests.cs
tools/slicec-cs/src/decoding.rs
tools/slicec-cs/src/encoding.rs

The `EncodeTagged` and `DecodeTagged` functions take a function pointer, for performing the actual encoding/decoding.
Currently the signature of those functions assume they're working with non-null types, because the 'null-ness' is handled by being tagged (present or not present).
There's an exception to this though: Slice1 proxies sent by an Ice client. Because these can be 'set' to 'null'.
This PR fixes the code-gen to handle this case.
Proxies (and `ServiceAddress`) are just custom types. So now, for tagged Slice1 custom types, the code-generator will use `(Encode|Decode)NullableCustomType` instead of `(Encode|Decode)CustomType`.
This will add a slight performance hit (which is fine, since this is incredibly niche), and requires removing a `notnull` type restriction from the `Slice1` …

Always Use Nullable Extension Methods for Tagged Slice1 Custom Types

---

src/IceRpc.Protobuf/IceRpc.Protobuf.csproj
tools/IceRpc.Protobuf.Tools/IceRpc.Protobuf.Tools.csproj
tools/IceRpc.ProtocGen/IceRpc.ProtocGen.csproj

This PR upgrades the Protobuf version used by IceRpc to the latest released 26.0 (3.26.0 NuGet package)

Upgrade Protobuf version to 3.26.0

---

.github/workflows/ci.yml
build/IceRpc.DocfxExamples.props
build/IceRpc.Examples.props
build/IceRpc.Version.props
tools/slicec-cs/Cargo.lock
tools/slicec-cs/Cargo.toml

This PR separates the "version number" used for the examples and the IceRPC assemblies. It also updates the slices cargo dep.
Additionally it moves the testing of the examples to a separate step job independent of the src build.

Separate example and assembly version and update Cargo deps

---

.github/actions/build-examples/action.yaml
.github/workflows/ci.yml
build/IceRpc.DocfxExamples.props

This PR changes updates the ci workflow to build the docfx examples against the local src build instead of the published NuGet packages.

Build docfx examples against src build

---

src/IceRpc.Templates/Templates/IceRpc-Protobuf-Client/IceRpc-Protobuf-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-DI-Client/IceRpc-Protobuf-DI-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-DI-Server/IceRpc-Protobuf-DI-Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-Server/IceRpc-Protobuf-Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-Client/IceRpc-Slice-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Client/IceRpc-Slice-DI-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Server/IceRpc-Slice-DI-Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-Server/IceRpc-Slice-Server.csproj

The templates should use the IceRpc assemblies built in this repository, as defined in `build/IceRpc.Version.props`.

Update IceRPC version used in project templates

---

src/IceRpc/Transports/SslAuthenticationOptionsExtensions.cs

The Clone extensions methods in SslAuthenticationOptionsExtensions are missing some new options.

Fix clone of authentication options

---

src/IceRpc.Transports.Quic/Internal/QuicExceptionExtensions.cs
tests/IceRpc.Quic.Tests/Transports/QuicIdleTimeoutTests.cs

This PR adds a first QUIC idle timeout test. It also fixes a small bug in the QUIC error mapping.
It's the initial step for fixing #3353 - first demonstrate the issue.

Add QUIC idle timeout test

---

build/CodeAnalysis.Tests.globalconfig
src/IceRpc/Transports/Internal/FlagEnumExtensions.cs
src/IceRpc/Transports/Slic/Internal/SlicStream.cs
tests/IceRpc.Tests.Common/TransportOperations.cs
tests/ZeroC.Slice.Tests/EnumWithFieldsTests.cs
tests/ZeroC.Slice.Tests/SequenceEncodingTests.cs

These are a few fixes to build IceRPC C# with dotnet 9.0. This PR does not include the build system fixes.

Fixes for dotnet 9.0

---

src/IceRpc/ConnectionOptions.cs
tests/IceRpc.Tests/IceProtocolConnectionTests.cs

This PR changes the default for ConnectionOptions.EnableIceIdleCheck. We are doing the same for Ice 3.8.

Change default for EnableIceIdleCheck to true

---

src/IceRpc/ServiceAddress.cs

This PR makes some minor improvements to comments and an error message in `ServiceAddress`.
----
'and' is more correct here because it's an "inclusive or", whereas 'or' functions like an "exclusive or".
And it's fine for a URI to contain both `%` _and_ unreserved characters.

Minor improvements to 'ServiceAddress' comments.

---

src/IceRpc/Internal/IceDuplexConnectionDecorator.cs
src/IceRpc/Internal/IceProtocolConnection.cs
tests/IceRpc.Tests/IceIdleTimeoutTests.cs

This PR makes small updates to the IceDuplexConnectionDecorator and related code:
- switch to the Ice terminology: heartbeat instead of "ping" and "keep alive"
- cancels the write timer before writing anything (like we do in Ice 3.8)

Improve/clean-up the Ice duplex connection decorator

---

src/IceRpc.Retry/RetryInterceptor.cs

This is a small enhancement to the Retry interceptor - it makes the decorator non-resettable on the last attempt to recycle the request memory as soon as possible.

Make decorator non-resettable on the last attempt

---

tools/IceRpc.Slice.Tools/SliceCCSharpTask.cs
tools/slicec-cs/Cargo.lock
tools/slicec-cs/Cargo.toml
tools/slicec-cs/src/cs_options.rs
tools/slicec-cs/src/main.rs

This PR is the cleaned up version of the additional output from `slicec-cs` from https://github.com/icerpc/icerpc-csharp/pull/4006. Notably, I did remove the updated files information. After discussion with @pepone I don't actually think we need this data point.

`metrics` flag for `slicec-cs` added

---

src/IceRpc/Pipeline.cs
src/IceRpc/Router.cs

This little clean-up PR cleans the interceptor and middleware stack once the pipeline in created.
This way, any memory held by these functions can be GCed immediately.

Clear interceptor/middleware stack

---

slice/IceRpc/Internal/IceDefinitions.slice
src/IceRpc.Slice/IncomingResponseExtensions.cs
src/IceRpc/Internal/IceProtocolConnection.cs
src/ZeroC.Slice/IActivator.cs
src/ZeroC.Slice/Internal/Activator.cs
src/ZeroC.Slice/SliceDecoder.Class.cs
src/ZeroC.Slice/SliceException.cs
tests/IceRpc.Slice.Tests/ExceptionTests.cs
tests/IceRpc.Slice.Tests/ExceptionTests.slice
tests/ZeroC.Slice.Tests/ActivatorTests.cs
tests/ZeroC.Slice.Tests/SlicingTests.cs
tests/ZeroC.Slice.Tests/TaggedTests.cs
tools/slicec-cs/src/builders.rs
tools/slicec-cs/src/generators/class_generator.rs
tools/slicec-cs/src/generators/exception_generator.rs

This PR simplifies Slice exceptions and the Slice activator (used to create class and exception instances from a Slice type ID).
Slice exceptions were more complicated than needed because for a while we wanted to use them with Slice2 too, but we abandoned this idea. So exceptions are:
- Slice1-only
- usually transmitted over the ice protocol
- conceptually similar to the error component of a Slice2 Result
This means the exception message (not transmitted by Slice1) and the inner exception (not meaningful) don't matter much. Note that the error component of a Slice2 Result does have these either.
So this PR removes the message and innerException parameters from the generated exception constructors. As a result, both generated classes and exceptions rely on the same parameterless …

Simplify Slice exceptions and Slice activator

---

tools/slicec-cs/src/generators/class_generator.rs
tools/slicec-cs/src/generators/exception_generator.rs
tools/slicec-cs/src/member_util.rs
tools/slicec-cs/src/slicec_ext/member_ext.rs

This PR updates the C# mapping for Slice classes and exceptions to use 'required' fields for non-nullable reference types.
Fixes #4014.

Use required fields in classes and exceptions

---

.vscode/cspell.json
tests/IceRpc.Quic.Tests/IceRpc.Quic.Tests.csproj
tests/IceRpc.Quic.Tests/Transports/QuicTransportServiceCollectionExtensions.cs
tests/IceRpc.Quic.Tests/Transports/QuicTransportSslAuthenticationTests.cs

This PR fixes CI failures related to use the deprecated X509Certificate2 constructor.
It uses the new [X509CertificateLoader](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificateloader?view=net-8.0) which is part of .NET 9 and available for .NET 8 in Microsoft.Bcl.Cryptography NuGet package.

Do not use deprecated certificate constructor

---

src/Directory.Build.props
tests/Directory.Build.props
tools/IceRpc.BuildTelemetry.Reporter/README.md
tools/IceRpc.Protobuf.Tools/IceRpc.Protobuf.Tools.props
tools/IceRpc.Protobuf.Tools/IceRpc.Protobuf.Tools.targets
tools/IceRpc.Slice.Tools/IceRpc.Slice.Tools.props
tools/IceRpc.Slice.Tools/IceRpc.Slice.Tools.targets

This PR renames two build telemetry properties:
- DisableBuildTelemetry => IceRpcBuildTelemetry
- TelemetryScriptPath => IceRpcTelemetryScriptPath
Fixes #4015

Rename property to enable/disable build telemetry

---

build/IceRpc.Src.props
src/Directory.Build.props

With .NET 8 is no longer required to setup source link, see https://github.com/dotnet/sourcelink/blob/main/README.md#using-source-link-in-net-projects
Fix #4017

Use default source link setup

---

tests/IceRpc.Logger.Tests/IceRpc.Logger.Tests.csproj
tests/IceRpc.Retry.Tests/IceRpc.Retry.Tests.csproj

This PR fixes the NuGet Audit build failures on main.

Fix NuGet Audit build failure

---

tools/IceRpc.Slice.Tools/BuildTelemetryTask.cs

This fixes a problem where the build telemetry failed to run because the current working directory was not correctly set.

Fix working directory for running build telemetry task

---

docfx/docfx.json

Fix #3993
`_gitContribute | object | Defines the repo and branch property of git links.` from https://dotnet.github.io/docfx/docs/template.html?tabs=modern
This is a template global setting disabled for all pages.

Disable docfx edit this page links

---

.github/actions/test-templates/action.yaml
.github/workflows/ci.yml

The `dotnet` command doesn't work well with the `bash` shell on Windows, updated to use `pwsh` (Powershell) works well across all platforms.

Use pwsh shell for template testing

---

tools/IceRpc.Protobuf.Tools/README.md
tools/IceRpc.Slice.Tools/README.md

This PR adds build telemetry section to the Protobuf and Slice tools packages.

Add buid telemetry notes to tools packages

---

src/IceRpc.Templates/Templates/IceRpc-Protobuf-Client/IceRpc-Protobuf-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-Client/Program.cs
src/IceRpc.Templates/Templates/IceRpc-Protobuf-Server/IceRpc-Protobuf-Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-Server/Program.cs
src/IceRpc.Templates/Templates/IceRpc-Slice-Client/IceRpc-Slice-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-Client/Program.cs
src/IceRpc.Templates/Templates/IceRpc-Slice-Server/IceRpc-Slice-Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-Server/Program.cs

This PR updates templates to setup SSL with tcp transport.

Use SSL with Protobuf and Slice templates

---

src/IceRpc.Templates/Templates/IceRpc-Protobuf-Client/.template.config/template.json
src/IceRpc.Templates/Templates/IceRpc-Protobuf-Server/.template.config/template.json
src/IceRpc.Templates/Templates/IceRpc-Slice-Client/.template.config/template.json
src/IceRpc.Templates/Templates/IceRpc-Slice-Server/.template.config/template.json

The 0.4.0 templates has an exclude condition for the certificates when using TCP transport, this PR removes it.

Do not exclude certificates when using tcp transport

---

build/IceRpc.Examples.props
src/IceRpc.Templates/Templates/IceRpc-Protobuf-Client/.template.config/template.json
src/IceRpc.Templates/Templates/IceRpc-Protobuf-Client/IceRpc-Protobuf-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-DI-Client/IceRpc-Protobuf-DI-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-DI-Server/IceRpc-Protobuf-DI-Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-Server/.template.config/template.json
src/IceRpc.Templates/Templates/IceRpc-Protobuf-Server/IceRpc-Protobuf-Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-Client/.template.config/template.json
src/IceRpc.Templates/Templates/IceRpc-Slice-Client/IceRpc-Slice-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Client/IceRpc-Slice-DI-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Server/IceRpc-Slice-DI-Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-Server/.template.config/template.json
src/IceRpc.Templates/Templates/IceRpc-Slice-Server/IceRpc-Slice-Server.csproj

This PR updates the examples and templates to use IceRpc 0.4.* instead of 0.4.0.

Use 0.4.* instead of 0.4.0

---

.github/workflows/release.yml
build/IceRpc.Examples.props
build/IceRpc.Version.props
src/IceRpc.Templates/Templates/IceRpc-Protobuf-Client/IceRpc-Protobuf-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-DI-Client/IceRpc-Protobuf-DI-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-DI-Server/IceRpc-Protobuf-DI-Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-Server/IceRpc-Protobuf-Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-Client/IceRpc-Slice-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Client/IceRpc-Slice-DI-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Server/IceRpc-Slice-DI-Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-Server/IceRpc-Slice-Server.csproj
tests/IceRpc.Tests.Common/IceRpc.Tests.Common.csproj

Update release workflow to build the reporter before packaging tools

---

.github/workflows/release.yml
build/IceRpc.Examples.props

This PR updates the release workflow to configure a local NuGet source for testing the packages and templates.
This PR fixes the issue of testing a new major release and using a range version for project templates and example projects.
With the previous setup if we set the range expression to `"0.5.*"`, when we are running the release workflow for the new major version `0.5.0`. The examples project and the new project templates would fail to build, because there is no published version that will match `"0.5.*"`.
Adding a local source with the packages for the new version fixes the issue.

Use a local NuGet source for the release workflow tests

---

.github/workflows/coverage.yml
.github/workflows/docs.yml

This PR updates the coverage and doc workflows to use `github.ref_name` instead of a hard coded branch name for the s3 path. 
This way there's nothing to update in this part of the workflows when we create a new branch of off `main`.

Use github.ref_name instead of hardcoded branch name

---

examples/protobuf/GenericHost/Server/Server.csproj
examples/protobuf/Quic/Server/Server.csproj
examples/protobuf/Secure/Server/Server.csproj
examples/protobuf/TcpFallback/Server/Server.csproj
examples/slice/GenericHost/Server/Server.csproj
examples/slice/Quic/Server/Server.csproj
examples/slice/Secure/Server/Server.csproj
examples/slice/TcpFallback/Server/Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-Client/IceRpc-Protobuf-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-DI-Client/IceRpc-Protobuf-DI-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-DI-Server/IceRpc-Protobuf-DI-Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Protobuf-Server/IceRpc-Protobuf-Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-Client/IceRpc-Slice-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Client/IceRpc-Slice-DI-Client.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Server/IceRpc-Slice-DI-Server.csproj
src/IceRpc.Templates/Templates/IceRpc-Slice-Server/IceRpc-Slice-Server.csproj
tests/IceRpc.Conformance.Tests/IceRpc.Conformance.Tests.csproj
tests/IceRpc.Logger.Tests/IceRpc.Logger.Tests.csproj
tests/IceRpc.Quic.Tests/IceRpc.Quic.Tests.csproj
tests/IceRpc.Retry.Tests/IceRpc.Retry.Tests.csproj
tests/IceRpc.Tests/IceRpc.Tests.csproj

Upgrade to use `9.0.*` packages instead of `9.0.0-preview.*` ones.

Upgrade packages for .NET 9 builds

---

tests/IceRpc.Tests/Transports/Tcp/TcpTransportTests.cs

Fix for Configure_server_connection_listen_backlog test

---

tests/IceRpc.Tests/Transports/Slic/SlicIdleTimeoutTests.cs
tests/IceRpc.Tests/Transports/Slic/SlicTransportTests.cs

Add NonParallelizable attribute to some time sensistive tests

---

tests/IceRpc.Tests/Transports/Slic/SlicTransportTests.cs

This is a small update to Slic's Connection_with_idle_timeout_and_slow_write_is_not_aborted test, in an effort to figure out #4108.
Note that the 500ms duration chosen by this test happens to match Slic's read timer:
https://github.com/icerpc/icerpc-csharp/blob/bcec78b14b3c216bac1a4413a5f595f8bd1b1a60/src/IceRpc/Transports/Slic/Internal/SlicDuplexConnectionDecorator.cs#L119
So, with the test as written, the test sends a (one-way) byte every 500ms and Slic sends a Ping frame every 500ms (to get back a Pong frame). Assuming a little latency, this 1-byte write should be written first in subsequent iterations since Slic resets its read timer when it reads the Pong frame. It's not clear if we chose 500ms to match the Slic read timer or if it's accidental.

Improve Slic slow write test

---

.editorconfig

In particular, we don't specify "public" on abstract methods in public interfaces.

Fix dotnet_style_require_accessibility_modifiers
