icerpc/icerpc-csharp

- src/IceRpc.Compressor/IceRpc.Compressor.csproj
- src/IceRpc.Deadline/IceRpc.Deadline.csproj
- src/IceRpc.Extensions.DependencyInjection/IceRpc.Extensions.DependencyInjection.csproj
- src/IceRpc.Locator/IceRpc.Locator.csproj
- src/IceRpc.Logger/IceRpc.Logger.csproj
- src/IceRpc.Metrics/IceRpc.Metrics.csproj
- src/IceRpc.RequestContext/IceRpc.RequestContext.csproj
- src/IceRpc.Retry/IceRpc.Retry.csproj
- src/IceRpc.Slice/IceRpc.Slice.csproj
- src/IceRpc.Telemetry/IceRpc.Telemetry.csproj
- src/IceRpc.Templates/IceRpc.Templates.csproj
- src/IceRpc.Transports.Coloc/IceRpc.Transports.Coloc.csproj
- src/IceRpc.Transports.Quic/IceRpc.Transports.Quic.csproj
- src/IceRpc/IceRpc.csproj
- src/ZeroC.Slice/ZeroC.Slice.csproj
- tests/IceRpc.Conformance.Tests/IceRpc.Conformance.Tests.csproj
- tests/IceRpc.Tests.Common/IceRpc.Tests.Common.csproj
> Use lower case tags

- build/IceRpc.Version.props
- src/IceRpc.Templates/Templates/IceRpc-Slice-Client/IceRpc-Slice-Client.csproj
- src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Client/IceRpc-Slice-DI-Client.csproj
- src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Server/IceRpc-Slice-DI-Server.csproj
- src/IceRpc.Templates/Templates/IceRpc-Slice-Server/IceRpc-Slice-Server.csproj
- tools/slicec-cs/Cargo.toml
Upgrade version for 0.1.1 release
> Upgrade version

- docfx/docfx.json
- docfx/index.md
Small fixes to the API reference home page.
> Fix API reference home page

- tests/ZeroC.Slice.Tests/StructTests.cs
- tests/ZeroC.Slice.Tests/StructTests.slice
- tools/slicec-cs/src/encoding.rs
Fixes issue #3663. This PR also incorporates the tests introduced in PR #3664.
> Encode optional enum

- src/IceRpc.Templates/Directory.Build.props
> Fix warning related to props files included multiple times

- src/IceRpc/Transports/IDuplexConnection.cs
> Fix DuplexConnection ReadAsync doc-comment

- .github/workflows/ci.yml
- .github/workflows/spellcheck.yml
- README.md
@externl, do you know how to upgrade the badge URL for referring to this branch?
> Run CI job on 0.1.x branch

- examples/README.md
This PR updates the examples README to explain how to build the examples.
> Describe branch and NuGet package version

- tests/IceRpc.Slice.Tests/OperationDerivedTests.slice
- tests/IceRpc.Slice.Tests/OperationTests.cs
- tests/IceRpc.Slice.Tests/OperationTests.slice
- tools/slicec-cs/src/generators/proxy_generator.rs
> Fix proxy generated code for calling Inherit operations

- src/IceRpc.Protobuf.Generators/Internal/Emitter.cs
- src/IceRpc.Protobuf.Generators/Internal/StringExtensions.cs
- src/IceRpc.Slice.Generators/Internal/Emitter.cs
- src/IceRpc.Slice.Generators/Internal/StringExtensions.cs
> Fix Inconsistent line endings in Service.g.cs

- src/IceRpc.Transports.Quic/Internal/QuicExceptionExtensions.cs
- tests/IceRpc.Conformance.Tests/Transports/MultiplexedListenerConformanceTests.cs
> Handle QuicError.AlpnInUse

- tests/IceRpc.Conformance.Tests/Transports/DuplexListenerConformanceTests.cs
- tests/IceRpc.Conformance.Tests/Transports/MultiplexedListenerConformanceTests.cs
- tests/IceRpc.Tests.Common/ClientServerDuplexConnection.cs
- tests/IceRpc.Tests.Common/ClientServerMultiplexedConnection.cs
> Add test to ensure disposing listener doesn't affect existing connections

- tools/slicec-cs/Cargo.lock
- tools/slicec-cs/Cargo.toml
Upgrade slicec-cs version on main to `0.2.0`
> Upgrade slicec-cs version

- examples/GreeterProtobuf/Client/Client.csproj
- examples/GreeterProtobuf/Server/Server.csproj
- tests/IceRpc.Protobuf.Tests/IceRpc.Protobuf.Tests.csproj
- tools/IceRpc.Protobuf.Tools/IceRpc.Protobuf.Tools.csproj
- tools/IceRpc.Protobuf.Tools/IceRpc.Protobuf.Tools.props
- tools/IceRpc.Protobuf.Tools/IceRpc.Protobuf.Tools.targets
> Bundle Google.Protobuf.Tools with IceRpc.Protobuf.Tools

- tools/IceRpc.ProtocGen/Program.cs
> Add missing new lines in ProtocGen generated code

- .vscode/cspell.json
- src/IceRpc.Protobuf.Generators/Internal/Emitter.cs
- src/IceRpc.Protobuf.Generators/Internal/Parser.cs
- src/IceRpc.Protobuf.Generators/Internal/ServiceMethod.cs
- src/IceRpc.Protobuf/AsyncEnumerableExtensions.cs
- src/IceRpc.Protobuf/InvokerExtensions.cs
- src/IceRpc.Protobuf/PipeReaderExtensions.cs
- src/IceRpc.Protobuf/ProtobufEncodeOptions.cs
- tests/IceRpc.Protobuf.Tests/OperationTests.cs
- tests/IceRpc.Protobuf.Tests/OperationTests.proto
- tests/IceRpc.Protobuf.Tests/ServiceTests.cs
- tools/IceRpc.ProtocGen/ClientGenerator.cs
- tools/IceRpc.ProtocGen/MessageDescriptorExtensions.cs
- tools/IceRpc.ProtocGen/Program.cs
- tools/IceRpc.ProtocGen/ServiceGenerator.cs
> Add support for protobuf streaming RPCs

- src/IceRpc.Protobuf/PipeReaderExtensions.cs
- tests/IceRpc.Protobuf.Tests/OperationTests.cs
- tests/IceRpc.Protobuf.Tests/OperationTests.proto
- tests/IceRpc.Protobuf.Tests/StreamTests.cs
- tests/IceRpc.Tests.Common/ColocInvoker.cs
- tools/IceRpc.ProtocGen/MessageDescriptorExtensions.cs
This PR adds additional tests for Protobuf support.
> Add more protobuf tests

- src/IceRpc.Protobuf.Generators/Internal/Parser.cs
- src/IceRpc.Protobuf/ProtobufMethodAttribute.cs
- tools/IceRpc.ProtocGen/ServiceGenerator.cs
> Rename ProtobufOperationAttribute -> ProtobufMethodAttribute

- tests/IceRpc.Protobuf.Tests/OperationTests.proto
> Fix Protobuf package name

- examples/protobuf/Stream/proto/generator.proto
- tests/IceRpc.Protobuf.Tests/OperationTests.proto
- tests/IceRpc.Protobuf.Tests/ServiceTests.cs
- tests/IceRpc.Protobuf.Tests/ServiceTests.proto
This PR adds two additional tests for the ProtobufService generated code:
- A class that implements multiple Protobuf services
- A class that uses ProtobufService, and doesn't directly implement the Protobuf generated services.
> Additional tests for ProtobufService

- src/IceRpc.Protobuf/InvokerExtensions.cs
- tools/IceRpc.ProtocGen/ClientGenerator.cs
This PR makes small fixes to InvokerExtensions.
> Improves InvokerExtensions

- src/ZeroC.Slice/SliceDecoder.cs
- tests/ZeroC.Slice.Tests/NumericTypesDecodingTests.cs
- tests/ZeroC.Slice.Tests/SequenceDecodingTests.cs
- tests/ZeroC.Slice.Tests/SequenceDecodingTests.slice
- tools/slicec-cs/src/decoding.rs
> Fix bool decoding to be strict

- tools/IceRpc.ProtocGen/ClientGenerator.cs
> Add missing protobuf encode options

- .github/actions/build-compiler/action.yaml
- .github/actions/test/action.yaml
> Replace deprecated actions-rs with dtolnay/rust-toolchain@stable

- tests/IceRpc.Protobuf.Tests/ServiceProviderExtensionsTests.cs
- tests/IceRpc.Slice.Tests/ServiceProviderExtensionsTests.cs
- tools/IceRpc.ProtocGen/ClientGenerator.cs
> Add tests for CreateSliceProxy & CreateProtobufClient

- tools/IceRpc.ProtocGen/IceRpc.ProtocGen.csproj
Fix #3837
I closed #3849 and opened this with target 0.2.x
> Do not generate NuGet package for IceRpc.ProtocGen -

- src/IceRpc.Templates/Templates/IceRpc-Protobuf-Client/Program.cs
- src/IceRpc.Templates/Templates/IceRpc-Protobuf-DI-Client/appsettings.json
- src/IceRpc.Templates/Templates/IceRpc-Protobuf-DI-Server/appsettings.json
- src/IceRpc.Templates/Templates/IceRpc-Protobuf-Server/Program.cs
- src/IceRpc.Templates/Templates/IceRpc-Slice-Client/Program.cs
- src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Client/appsettings.json
- src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Server/appsettings.json
- src/IceRpc.Templates/Templates/IceRpc-Slice-Server/Program.cs
> Update log level used by project templates

- tools/slicec-cs/src/generators/enum_generator.rs
This PR updates the implementation of the DecodeXxx extension method, when Xxx is an enum with fields.
The implementation is now using local functions instead of FromSliceDecoder helper methods on the enumerator classes.
I initially wanted to do the same for EncodeXxx, but finally kept the existing logic. I just updated to code to make the helper internal Encode methods "never editor browsable".
> Update enum with field Decode implementation

- tests/ZeroC.Slice.Tests/EnumWithFieldsTests.cs
- tools/slicec-cs/src/builders.rs
- tools/slicec-cs/src/generators/enum_generator.rs
> Rework generated unknown, remove top-level Discriminant property

- tests/ZeroC.Slice.Tests/EnumWithFieldsTests.cs
- tests/ZeroC.Slice.Tests/EnumWithFieldsTests.slice
- tools/slicec-cs/Cargo.lock
- tools/slicec-cs/Cargo.toml
- tools/slicec-cs/src/generators/enum_generator.rs
This PR adds support for compact enum with fields in C#.
> Add support for compact enum with fields

- .vscode/settings.json
This PR updates this repo to use the configuration sets added in https://github.com/zeroc-ice/vscode-slice/releases/tag/v4.3.0.
> Update slice extension settings to use configuration sets

- README.md
This tiny PR updates the top-level README to mention Result.
> Mention Result<Success, Failure> in top-level README

- .vscode/settings.json
This PR adds missing slice configurations.
Fixes #3896
> Add Slice configuration for tests and CustomError example

- .github/workflows/release.yml
> Add workflow step to test release packages

- tests/ZeroC.Slice.Tests/ResultTests.slice
- tools/slicec-cs/src/decoding.rs
This PR fixes #3898 and adds some test cases to hit it.
This was the same bug as #3881.
> Fixed Results Containing Optional Collections

- examples/protobuf/README.md
- examples/protobuf/TcpFallback/Client/Client.csproj
- examples/protobuf/TcpFallback/Client/Program.cs
- examples/protobuf/TcpFallback/README.md
- examples/protobuf/TcpFallback/Server/Chatbot.cs
- examples/protobuf/TcpFallback/Server/Program.cs
- examples/protobuf/TcpFallback/Server/Server.csproj
- examples/protobuf/TcpFallback/TcpFallback.sln
- examples/protobuf/TcpFallback/proto/greeter.proto
- examples/slice/README.md
It's identical to the Slice version I merged earlier, except it uses Protobuf.
> Protobuf version of the TCP fallback example

- examples/json/Greeter/Server/Chatbot.cs
- examples/json/Greeter/Server/Program.cs
- examples/protobuf/Logger/Server/Chatbot.cs
- examples/protobuf/Logger/Server/Program.cs
- examples/protobuf/MultipleServices/Server/Chatbot.cs
- examples/protobuf/MultipleServices/Server/Program.cs
- examples/protobuf/Stream/Server/Program.cs
- examples/protobuf/Stream/Server/RandomGenerator.cs
- examples/slice/CustomError/Server/Chatbot.cs
- examples/slice/CustomError/Server/Program.cs
- examples/slice/Logger/Server/Chatbot.cs
- examples/slice/Logger/Server/Program.cs
- examples/slice/Quic/Server/Chatbot.cs
- examples/slice/Quic/Server/Program.cs
- examples/slice/Stream/Server/Program.cs
- examples/slice/Stream/Server/RandomGenerator.cs
This PR fixes the server namespaces in the examples.
FIxes #3910.
> Fix server namespaces

- tests/IceRpc.Conformance.Tests/Transports/DuplexConnectionConformanceTests.cs
- tests/IceRpc.Conformance.Tests/Transports/MultiplexedConnectionConformanceTests.cs
- tests/IceRpc.Conformance.Tests/Transports/MultiplexedStreamConformanceTests.cs
- tests/IceRpc.Locator.Tests/CacheLessLocationResolverTests.cs
- tests/IceRpc.Slice.Tests/ClassTests.cs
- tests/IceRpc.Tests/IceRpcProtocolConnectionTests.cs
- tests/IceRpc.Tests/ServerTests.cs
- tests/IceRpc.Tests/Transports/Slic/SlicTransportTests.cs
- tests/IceRpc.Tests/Transports/Tcp/TcpTransportTests.cs
- tests/ZeroC.Slice.Tests/ResultTests.cs
- tests/ZeroC.Slice.Tests/SequenceEncodingTests.cs
Probably fine, but just wanted another pair of eyes to make sure.
> Cleanup 'Values' Usage in the Tests

- .vscode/cspell.json
- build/IceRpc.Version.props
- src/IceRpc.Templates/Templates/IceRpc-Protobuf-Client/IceRpc-Protobuf-Client.csproj
- src/IceRpc.Templates/Templates/IceRpc-Protobuf-DI-Client/IceRpc-Protobuf-DI-Client.csproj
- src/IceRpc.Templates/Templates/IceRpc-Protobuf-DI-Server/IceRpc-Protobuf-DI-Server.csproj
- src/IceRpc.Templates/Templates/IceRpc-Protobuf-Server/IceRpc-Protobuf-Server.csproj
- src/IceRpc.Templates/Templates/IceRpc-Slice-Client/IceRpc-Slice-Client.csproj
- src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Client/IceRpc-Slice-DI-Client.csproj
- src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Server/IceRpc-Slice-DI-Server.csproj
- src/IceRpc.Templates/Templates/IceRpc-Slice-Server/IceRpc-Slice-Server.csproj
- tools/slicec-cs/Cargo.lock
- tools/slicec-cs/Cargo.toml
This PR updates the version, and pulls in 2 commits that are on main, which would be nice to have on 0.3.x as well:
fixes to the language extension settings.
This will cause some merge conflicts with my other PR, which I'll deal with.
> Update version to '0.3.1-preview1'.

- .github/workflows/ci.yml
This PR fixes CI job on 0.3.x branch, to run for push/pull_request on this branch.
> Enable CI on 0.3.x branch

- tools/IceRpc.Protobuf.Tools/IceRpc.Protobuf.Tools.targets
> Fix UpToDate condition in ProtoBuf.Tools

- .github/actions/test-templates/action.yaml
- .github/workflows/ci.yml
- .github/workflows/release.yml
> Run `test-templates` action in release workflow

- .github/actions/build-compiler/action.yaml
- .github/actions/build/action.yaml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/spellcheck.yml
- slice/.github/workflows/spellcheck.yml
The release workflow run https://github.com/icerpc/icerpc-csharp/actions/runs/8471930544 shows some warnings about using Node 16 actions. This PR updates the relevant actions to Node 20.
> Transition to Node 20 actions

- .github/workflows/release.yml
> Disable template testing on Windows

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- build/Common.props
> Work around for NuGet audit failures

- tools/slicec-cs/src/generators/class_generator.rs
- tools/slicec-cs/src/generators/exception_generator.rs
Slice class and Slice exceptions are very similar, so it makes sense for class generator and exception generator to be very similar.
This PR synchronizes these 2 implementations, starting with the existing class_generator implementation.
> Synchronize class_generator and exception_generator

- src/IceRpc.Locator/LocatorInterceptor.cs
- tests/IceRpc.Locator.Tests/LocationResolverTests.cs
- tools/IceRpc.ProtocGen/ClientGenerator.cs
- tools/slicec-cs/src/builders.rs
- tools/slicec-cs/src/generators/class_generator.rs
- tools/slicec-cs/src/generators/exception_generator.rs
- tools/slicec-cs/src/generators/proxy_generator.rs
- tools/slicec-cs/src/generators/struct_generator.rs
- tools/slicec-cs/src/slicec_ext/member_ext.rs
> Add 'required' to non-nullable struct fields

- src/ZeroC.Slice/ZeroC.Slice.csproj
> Emit Dunet generated code in ZeroC.Slice

- tests/IceRpc.Tests/ConnectionCacheTests.cs
This PR adds a new connection cache test to verify that the connection cache correctly selects an (the) alt server when the primary server is busy because it reached MaxConnections.
This test includes two test cases - for ice and icerpc.
A concern however is:
- the ConnectionCache implementation relies on specific error codes to "move next": 
https://github.com/icerpc/icerpc-csharp/blob/b1f65d8d66b671c9948c7bfb04c3881243ba6a96/src/IceRpc/ConnectionCache.cs#L494
- the MaxConnections test suggests we can get IceRpcError.IceRpcError with the ice protocol
https://github.com/icerpc/icerpc-csharp/blob/b1f65d8d66b671c9948c7bfb04c3881243ba6a96/tests/IceRpc.Tests/ServerTests.cs#L84
(this MaxConnections test uses the default transport (tcp), while all the connection cache tests use coloc)
> Add new connection cache test

- .github/workflows/coverage.yml
- README.md
This PR adds support for reporting coverage to coveralls.io
> Add code coverage reporting to coveralls.io

- README.md
Add report generator coverage link. Also keeping the coveralls link.
> readme report generator

- examples/protobuf/GenericHost/Server/Program.cs
- examples/protobuf/GenericHost/Server/Server.csproj
- examples/protobuf/Quic/Server/Program.cs
- examples/protobuf/Quic/Server/Server.csproj
- examples/protobuf/Secure/Server/Program.cs
- examples/protobuf/Secure/Server/Server.csproj
- examples/protobuf/TcpFallback/Server/Program.cs
- examples/protobuf/TcpFallback/Server/Server.csproj
- examples/slice/GenericHost/Server/Program.cs
- examples/slice/GenericHost/Server/Server.csproj
- examples/slice/Quic/Server/Program.cs
- examples/slice/Quic/Server/Server.csproj
- examples/slice/Secure/Server/Program.cs
- examples/slice/Secure/Server/Server.csproj
- examples/slice/TcpFallback/Server/Program.cs
- examples/slice/TcpFallback/Server/Server.csproj
> Upgrade examples to use ServerCertificateContext

- examples/protobuf/GenericHost/Server/Program.cs
- examples/protobuf/Quic/Server/Program.cs
- examples/protobuf/Secure/Server/Program.cs
- examples/protobuf/TcpFallback/Server/Program.cs
- examples/slice/GenericHost/Server/Program.cs
- examples/slice/Quic/Server/Program.cs
- examples/slice/Secure/Server/Program.cs
- examples/slice/TcpFallback/Server/Program.cs
- tests/IceRpc.Quic.Tests/Transports/QuicTransportServiceCollectionExtensions.cs
- tests/IceRpc.Quic.Tests/Transports/QuicTransportSslAuthenticationTests.cs
> Mark certificate keys as exportable for compatibility with macOS

- src/IceRpc.Templates/Templates/IceRpc-Protobuf-Client/IceRpc-Protobuf-Client.csproj
- src/IceRpc.Templates/Templates/IceRpc-Protobuf-Client/Program.cs
- src/IceRpc.Templates/Templates/IceRpc-Protobuf-DI-Client/IceRpc-Protobuf-DI-Client.csproj
- src/IceRpc.Templates/Templates/IceRpc-Protobuf-DI-Server/IceRpc-Protobuf-DI-Server.csproj
- src/IceRpc.Templates/Templates/IceRpc-Protobuf-Server/IceRpc-Protobuf-Server.csproj
- src/IceRpc.Templates/Templates/IceRpc-Protobuf-Server/Program.cs
- src/IceRpc.Templates/Templates/IceRpc-Slice-Client/IceRpc-Slice-Client.csproj
- src/IceRpc.Templates/Templates/IceRpc-Slice-Client/Program.cs
- src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Client/IceRpc-Slice-DI-Client.csproj
- src/IceRpc.Templates/Templates/IceRpc-Slice-DI-Server/IceRpc-Slice-DI-Server.csproj
- src/IceRpc.Templates/Templates/IceRpc-Slice-Server/IceRpc-Slice-Server.csproj
- src/IceRpc.Templates/Templates/IceRpc-Slice-Server/Program.cs
> Fix certificate loading in project templates

- .github/actions/test-templates/action.yaml
- .github/workflows/release.yml
> Fix project template testing

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/coverage.yml
- .github/workflows/docs.yml
- .github/workflows/rustfmt.yml
- .github/workflows/spellcheck.yml
Updates the 0.4.x branch workflows to trigger on said branch.
> Update main -> 0.4.x

- src/ZeroC.Slice/README.md
> Update ZeroC.Slice README

- tests/IceRpc.Conformance.Tests/IceRpc.Conformance.Tests.csproj
- tests/IceRpc.Logger.Tests/IceRpc.Logger.Tests.csproj
- tests/IceRpc.Retry.Tests/IceRpc.Retry.Tests.csproj
> Fix .NET 9 RC2 build failures

- tests/IceRpc.Conformance.Tests/Transports/DuplexListenerConformanceTests.cs
> Rework Connect_fails_if_listener_is_disposed test

- src/IceRpc/Transports/IDuplexConnection.cs
> Add remarks to IDuplexConnection

- src/IceRpc/Transports/IDuplexConnection.cs
- tests/IceRpc.Conformance.Tests/Transports/DuplexListenerConformanceTests.cs
- tests/IceRpc.Tests/Transports/Slic/SlicIdleTimeoutTests.cs
- tests/IceRpc.Tests/Transports/Slic/SlicTransportTests.cs
- tests/IceRpc.Tests/Transports/Tcp/TcpTransportTests.cs
Cherry pick latest fixes from main
> 0.4.x backports

- build/IceRpc.Version.props
> Update version to 0.4.2-preview1
